# shellcheck disable=SC1090,SC2148

# Powerlevel9k theme configuration
POWERLEVEL9K_MODE="nerdfont-complete"

# Terminal Segment
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR=''
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR=''

char() {
	echo -n "➜"
}
POWERLEVEL9K_CUSTOM_CHAR="char"
POWERLEVEL9K_CUSTOM_CHAR_BACKGROUND="none"
POWERLEVEL9K_CUSTOM_CHAR_FOREGROUND="white"

# Prompt Elements.
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
	date
	# go_version
	# node_version
	# php_version
	# anaconda
	# rbenv
	# swift_version
	# java_version
	# docker_machine
	newline
	context
	dir
	dir_writable_joined
	vcs
	newline
	root_indicator
	os_icon
	battery
	custom_char
)

POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
	status
	command_execution_time_joined
	background_jobs_joined
	vi_mode
)

# Styling prompt
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

# Date and Time
POWERLEVEL9K_DATE_FORMAT="%D{%a %d %b %y %H:%M:%S}"
POWERLEVEL9K_DATE_BACKGROUND='none'
POWERLEVEL9K_DATE_FOREGROUND="white"

# Version Control Styling
POWERLEVEL9K_VCS_GIT_HOOKS=(vcs-detect-changes git-untracked git-aheadbehind git-remotebranch git-stash git-tagname)
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='none'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND="white"
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='none'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="red"
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='none'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="yellow"

# Show Git Commit Hash
POWERLEVEL9K_CHANGESET_HASH_LENGTH=6
POWERLEVEL9K_SHOW_CHANGESET=true

# Directory Styling
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='none'
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="blue"
POWERLEVEL9K_DIR_HOME_BACKGROUND='none'
POWERLEVEL9K_DIR_HOME_FOREGROUND="white"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='none'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="white"
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND='none'
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="red"

# Directory Truncation
# POWERLEVEL9K_DIR_OMIT_FIRST_CHARACTER=true
POWERLEVEL9K_HOME_FOLDER_ABBREVIATION=' ~'
POWERLEVEL9K_SHORTEN_DIR_LENGTH=4
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"

# Vi-mode Stylings
POWERLEVEL9K_VI_INSERT_MODE_STRING="\uf040"
POWERLEVEL9K_VI_COMMAND_MODE_STRING="\ue7c5"
POWERLEVEL9K_VI_MODE_INSERT_FOREGROUND='none'
POWERLEVEL9K_VI_MODE_INSERT_BACKGROUND='none'
POWERLEVEL9K_VI_MODE_NORMAL_BACKGROUND='none'

# Root Indicator Styling
POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND="red"
POWERLEVEL9K_ROOT_INDICATOR_FOREGROUND="white"

# Return Status Styling
POWERLEVEL9K_STATUS_OK_ICON='\uf42e'
POWERLEVEL9K_STATUS_ERROR_BACKGROUND='none'
POWERLEVEL9K_STATUS_ERROR_FOREGROUND="red"
POWERLEVEL9K_STATUS_OK_BACKGROUND='none'
POWERLEVEL9K_STATUS_OK_FOREGROUND="green"
POWERLEVEL9K_STATUS_HIDE_SIGNAME=true

# Execution Time Styling
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='none'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='magenta'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=1
POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=2

# OS Icon
POWERLEVEL9K_OS_ICON_BACKGROUND='none'
POWERLEVEL9K_OS_ICON_FOREGROUND="249"

# Version Control Icons
POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON='\u2193'
POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON='\u2191'
POWERLEVEL9K_VCS_STAGED_ICON='\u00b1'
POWERLEVEL9K_VCS_UNSTAGED_ICON='\u00b1'
POWERLEVEL9K_VCS_UNTRACKED_ICON='\u25CF'

# Battery Indicator Styling
POWERLEVEL9K_BATTERY_VERBOSE=false
POWERLEVEL9K_BATTERY_LOW_THRESHOLD=25
POWERLEVEL9K_BATTERY_ICON=''

POWERLEVEL9K_BATTERY_CHARGED_BACKGROUND='none'
POWERLEVEL9K_BATTERY_CHARGED_FOREGROUND="green"
POWERLEVEL9K_BATTERY_CHARGING_BACKGROUND='none'
POWERLEVEL9K_BATTERY_CHARGING_FOREGROUND="blue"
POWERLEVEL9K_BATTERY_DISCONNECTED_BACKGROUND='none'
POWERLEVEL9K_BATTERY_DISCONNECTED_FOREGROUND="yellow"
POWERLEVEL9K_BATTERY_LOW_BACKGROUND='none'
POWERLEVEL9K_BATTERY_LOW_FOREGROUND="red"
